on:
    issues:
        types:
            - opened

permissions:
    issues: write  # Allow the workflow to update the opened issue

jobs:
    comment:
        if: startsWith(github.event.issue.title, '@bioimageiobot, please upload')
        outputs:
          package_url: ${{steps.analyse-body.outputs.package_url}}
        runs-on: ubuntu-latest
        steps:
          - id: analyse-body
            shell: python
            run: |
              import os

              body = os.environ["BODY"]

              expected_start = """## Terms of Service
              - [x] I confirm that I have read and agree to bioimage.io's [Terms of Service](https://bioimage.io/docs/#/terms_of_service)

              ## Temporary Public Download URL
              For the duration of the upload process I provide a publicly accessible download URL of my packaged resource description zip-archive:
              """
              if body.startswith(expected_start):
                package_url = body[len(expected_start):].split("\n")[0].strip()
                if not package_url or not isinstance(package_url, str) or not package_url.startwith("https://"):
                  msg = f"I was expecting to find an https URL to a ZIP-file containing a packaged bioimage.io description, but I found '{package_url}'."
                  package_url = ""
                else:
                  msg = f"Attempting to upload package source '{package_url}' to the bioimage.io collection..."
              else:
                msg = f"Expected issue body to start with the '@bioimageiobot, please upload' issue body template with a checked Terms of Service checkbox.\nPlease create a new issue if you do want to upload a bioimage.io package. Thank you! :pray:"
                package_url = ""

              with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
                print(f'message={msg}', file=fh)
                print(f'package_url={package_url}', file=fh)

            env:
              BODY: ${{github.event.issue.body}}

          - run: gh issue comment "$NUMBER" --body "$MESSAGE"
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              GH_REPO: ${{ github.repository }}
              NUMBER: ${{ github.event.issue.number }}
              MESSAGE: ${{steps.analyse-body.outputs.message}}

    stage:
        needs: comment
        if: needs.comment.outputs.package_url != ''
        uses: bioimage-io/collection/.github/workflows/stage_call.yaml@main
        with:
            package_url: ${{github.event.issue.body}}
            environment_name: production
            bioimageio_user_id: ${{format('github|{0}', github.event.issue.user.login)}}
        secrets: inherit

    report:
        needs: [comment, stage]
        if: always()
        runs-on: ubuntu-latest
        steps:
          - if: needs.stage.result != 'success'
            run: gh issue comment "$NUMBER" --body "$MESSAGE"
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              GH_REPO: ${{ github.repository }}
              NUMBER: ${{ github.event.issue.number }}
              MESSAGE: |
                Unfortunately an error occurred, see [logs of the staging workflow](${{github.server_url}}/${{github.repository}}/actions/runs/${{needs.stage.outputs.run_id}}).

                bioimage.io @reviewers were notified.

          - if: needs.stage.result == 'success'
            run: gh issue close "$NUMBER" --reason="$REASON"
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              GH_REPO: ${{ github.repository }}
              NUMBER: ${{ github.event.issue.number }}
              REASON: |
                Successfully staged new draft from ${{needs.comment.outputs.package_url}} ! :rocket:

                Status and test results of your upload can be found in our [draft overview](https://bioimageio-uploader.netlify.app/#/status).

